services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_DATABASE=family_health'
      - 'MYSQL_USER=hgbaodev'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql_data:/var/lib/mysql'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/data'
volumes:
  mysql_data:
  redis_data: