const BACKEND_ENDPOINT = import.meta.env.VITE_BACKEND_ENDPOINT;
const APP_ENDPOINT = import.meta.env.VITE_APP_ENDPOINT;
const GOOGLE_OAUTH_CLIENT_ID = import.meta.env.VITE_GOOGLE_OAUTH_CLIENT_ID;

export { BACKEND_ENDPOINT, APP_ENDPOINT, GOOGLE_OAUTH_CLIENT_ID };