spring:
  datasource:
    url: jdbc:mysql://localhost:3306/j2ee
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
